In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [4]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.neighbors import KNeighborsRegressor

In [5]:
knn=KNeighborsRegressor()

In [6]:
kfold=KFold(n_splits=5,shuffle=True,random_state=1)
scores=cross_val_score(knn,X,y,cv=kfold,scoring='r2')

In [7]:
scores.mean()

np.float64(0.4761976351913221)

### Apply GridSearchCV

In [8]:
from sklearn.model_selection import GridSearchCV
knn=KNeighborsRegressor()

In [9]:
grid={
    'n_neighbors':[1,3,5,7,9,11,12,15,20,31],
    'algorithm':['auto','ball_tree','kd_tree','brute'],
    'weights':['uniform','distance'],
    'p':[1,2,3,4]
}

In [10]:
gsv=GridSearchCV(knn,grid,cv=kfold,scoring='r2',verbose=2,n_jobs=-1)

In [11]:
gsv.fit(X,y)

Fitting 5 folds for each of 320 candidates, totalling 1600 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
             estimator=KNeighborsRegressor(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 12, 15, 20, 31],
                         'p': [1, 2, 3, 4],
                         'weights': ['uniform', 'distance']},
             scoring='r2', verbose=2)

In [13]:
gsv.best_params_

{'algorithm': 'auto', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [14]:
gsv.best_score_

np.float64(0.6117139367845081)

In [ ]:
pd.DataFrame(gsv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.032570,0.000562,0.013045,0.000945,auto,1,1,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'p': 1...",0.573689,0.286948,0.522222,0.308922,0.440975,0.426551,0.113434,213
1,0.023600,0.010625,0.011816,0.002038,auto,1,1,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'p': 1...",0.573689,0.286948,0.522222,0.308922,0.440975,0.426551,0.113434,217
2,0.010938,0.002813,0.008679,0.000759,auto,1,2,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'p': 2...",0.360926,0.206504,0.519969,0.272539,0.297671,0.331522,0.106425,285
3,0.007473,0.000946,0.009558,0.002701,auto,1,2,distance,"{'algorithm': 'auto', 'n_neighbors': 1, 'p': 2...",0.360926,0.206504,0.519969,0.272539,0.297671,0.331522,0.106425,290
4,0.005937,0.001358,0.013273,0.002878,auto,1,3,uniform,"{'algorithm': 'auto', 'n_neighbors': 1, 'p': 3...",0.360114,0.209324,0.509856,0.260005,0.181457,0.304151,0.119533,297
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,0.003931,0.001851,0.005787,0.002506,brute,31,2,distance,"{'algorithm': 'brute', 'n_neighbors': 31, 'p':...",0.429904,0.371584,0.533539,0.360635,0.475582,0.434249,0.064702,204
316,0.003284,0.000256,0.025468,0.002958,brute,31,3,uniform,"{'algorithm': 'brute', 'n_neighbors': 31, 'p':...",0.274002,0.248727,0.410349,0.238357,0.324105,0.299108,0.063022,305
317,0.005699,0.003236,0.028403,0.006610,brute,31,3,distance,"{'algorithm': 'brute', 'n_neighbors': 31, 'p':...",0.402180,0.350171,0.511542,0.344394,0.460677,0.413793,0.064423,229
318,0.004763,0.000459,0.026234,0.002011,brute,31,4,uniform,"{'algorithm': 'brute', 'n_neighbors': 31, 'p':...",0.266294,0.245304,0.398533,0.224579,0.306713,0.288285,0.061455,309
319,0.003518,0.000683,0.028986,0.003274,brute,31,4,distance,"{'algorithm': 'brute', 'n_neighbors': 31, 'p':...",0.391160,0.342460,0.499994,0.331964,0.447655,0.402646,0.063644,237

### RandomizedSearchCV

In [16]:
from sklearn.model_selection import RandomizedSearchCV
rsv=RandomizedSearchCV(knn,grid,cv=kfold,scoring='r2',verbose=2,n_jobs=-1)

In [21]:
rsv.fit(X,y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
                   estimator=KNeighborsRegressor(), n_jobs=-1,
                   param_distributions={'algorithm': ['auto', 'ball_tree',
                                                      'kd_tree', 'brute'],
                                        'n_neighbors': [1, 3, 5, 7, 9, 11, 12,
                                                        15, 20, 31],
                                        'p': [1, 2, 3, 4],
                                        'weights': ['uniform', 'distance']},
                   scoring='r2', verbose=2)

In [22]:
rsv.best_params_

{'weights': 'distance', 'p': 1, 'n_neighbors': 3, 'algorithm': 'kd_tree'}

In [23]:
rsv.best_score_

np.float64(0.5809033277350932)